app/blueprints/higher_lower.py
from flask import Blueprint, render_template, session, request, jsonify
import random
from ..models import Pokemon
from ..utils import get_data_full, get_all_generations, get_all_attributes, sort_pkmn, transform_stat_number, game_end, clean_session

# Blueprint for the Higher-Lower game views and logic
higher_lower_bp = Blueprint('higher_lower', __name__, template_folder='../templates')

# Retrieve all available generations and attributes from configuration (config.py)
all_generations = get_all_generations()
all_attributes = get_all_attributes()

# Serve the home page for the Higher Lower game, which includes instructions and settings.
# Also, clear any existing game session data to ensure a fresh start for the user.
@higher_lower_bp.route('/higher_lower_home', methods=['GET', 'POST'])
def home():
    clean_session('all')
    return render_template('higher_lower_home.html')

# Route to initiate and handle gameplay interactions for the Higher Lower game.
# It presents the game interface to the user and processes their input during the game.
@higher_lower_bp.route('/higher_lower', methods=['GET', 'POST'])
def start_game():
    # Retrieve the full database
    data_full = get_data_full()

    # Retrieve user game settings
    if request.method == 'POST':
        if 'gen' not in session and 'attributes' not in session:
            session['gen']  = request.form.getlist('gen[]')
            session['attributes'] = request.form.getlist('attributes[]')

        # If the game has ended, redirect to the score page
        result = game_end('hl')
        if result:
            return result

    # Clean the session cache
    clean_session('reset_hl')

    # Initialize the score count
    session['score'] = 0
    # Retrieve the user's high score, or initialize it as 0 if it's the user's first game
    session['high_score_hl'] = session.get('high_score_hl', 0)
    # Retrieve the list of already drawn Pokémon IDs; initialize as an empty list if none
    session['list_id'] = session.get('list_id', [])
    
    # Retrieve the list of attributes selected by the user; default to all attributes if none are selected
    stats = session.get('attributes', all_attributes)
    # Choose a random stat from the list of stats
    random_stat = random.choice(stats)

    # Retrieve the list of generations selected by the user; default to all generations if none are selected
    generation = session.get('gen', all_generations)
    # Filter the database based on the generations selected by the user
    data = data_full.query('generation in @generation')

    # Draw Pokemon 1
    pkmn_1 = sort_pkmn(data, random_stat)
    # Draw Pokemon 2
    pkmn_2 = sort_pkmn(data, random_stat)

    # Save in session cache the last Pokemon 1 and 2 ID's
    session['last_pkmn_1_id'] = pkmn_1.id
    session['last_pkmn_2_id'] = pkmn_2.id

    # Retrieve the list of user correct answers; initialize as an empty list if none
    session['pkmn_list'] = session.get('pkmn_list', [])
    # Create a dictionary with a random stat, the Pokémon's name, and the respective stat value
    # This dictionary is used to record the user's answer history
    battle = battle = {
        "stat": random_stat,
        "name1": pkmn_1.name,
        "stat1": transform_stat_number(pkmn_1.stat, random_stat), 
        "name2": pkmn_2.name,
        "stat2": transform_stat_number(pkmn_2.stat, random_stat)
    }
    session['pkmn_list'].append(battle)

    return render_template('higher_lower.html', stat=random_stat, pkmn_1=pkmn_1, pkmn_2=pkmn_2, high_score_hl=session.get('high_score_hl', 0))

# Redraw Pokemon after a correct answer
@higher_lower_bp.route('/redraw_pokemons_hl', methods=['GET', 'POST'])
def redraw_pokemons():
    # Retrieve the full database
    data_full = get_data_full()

    # Increase user score by 1
    session['score'] += 1

    # Variable to flag if the game ended
    game_end = 'False'

    # Get the ID of last selected Pokemon
    last_id = request.args.get('last_id')

    # Retrieve the list of attributes selected by the user; default to all attributes if none are selected
    stats = session.get('attributes', all_attributes)
    # Choose a random stat from the list of stats
    random_stat = random.choice(stats)

    # Retrieve the list of generations selected by the user; default to all generations if none are selected
    generation = session.get('gen', all_generations)
    # Filter the database based on the generations selected by the user
    data = data_full.query('generation in @generation')

    # Check if all Pokémons have been encountered to determine if the game has ended
    if len(session.get('list_id', [])) == len(data):
        game_end = 'True'
        return jsonify({
        'game_end': game_end
        })

    # Draw new Pokemon
    new_pokemon = sort_pkmn(data, random_stat)

    # Determine which previously selected Pokémon to replace with the new one
    if last_id == 'pkmn-1':
        id_pkmn_old = session['last_pkmn_1_id']
        session['last_pkmn_2_id'] = new_pokemon.id
    else:
        id_pkmn_old = session['last_pkmn_2_id']
        session['last_pkmn_1_id'] = new_pokemon.id

    # Retrieve details of the previously selected Pokémon based on its ID
    old_name = data[data['id'] == id_pkmn_old]['name'].iloc[0]
    old_id_name = data[data['id'] == id_pkmn_old]['id_name'].iloc[0]
    stat_pkmn_old = data[data['id'] == id_pkmn_old][random_stat].iloc[0]
    sprite_old = data[data['id'] == id_pkmn_old]['url_sprite'].iloc[0]
    old_pokemon = Pokemon(id_pkmn_old, old_name, old_id_name, stat_pkmn_old, sprite_old)

    # Record user answer history based on last selected Pokémon
    if last_id == 'pkmn-1':
        battle = {
        "stat": random_stat,
        "name1": old_pokemon.name,
        "stat1": transform_stat_number(old_pokemon.stat, random_stat),
        "name2": new_pokemon.name,
        "stat2": transform_stat_number(new_pokemon.stat, random_stat)
        }
    else:
        battle = {
        "stat": random_stat,
        "name1": new_pokemon.name,
        "stat1": transform_stat_number(new_pokemon.stat, random_stat),
        "name2": old_pokemon.name,
        "stat2": transform_stat_number(old_pokemon.stat, random_stat)
        }
    session['pkmn_list'].append(battle)

    # Return the game status, the newly drawn stat, the new Pokémon details, 
    # and the details of the Pokémon to be retained
    return jsonify({
        'game_end': game_end,
        'random_stat': random_stat,
        'new_pokemon': {
            'id': new_pokemon.id,
            'name': new_pokemon.name,
            'stat': transform_stat_number(new_pokemon.stat, random_stat),
            'sprite': new_pokemon.sprite
        },
        'old_pokemon': {
            'id': old_pokemon.id,
            'name': old_pokemon.name,
            'stat': transform_stat_number(old_pokemon.stat, random_stat),
            'sprite': old_pokemon.sprite
        }
    })

app/blueprints/home.py
from flask import Blueprint, render_template
from ..utils import clean_session

# Blueprint for Home views and logic
home_bp = Blueprint('home', __name__)

# Serve the home page
# Also, clear any existing game session data to ensure a fresh start for the user.
@home_bp.route('/')
def index():
    clean_session('all')
    return render_template('index.html')

app/blueprints/whos_that_pkmn.py
from flask import Blueprint, render_template, session, request, jsonify
from ..utils import sort_pkmn, clean_session, game_end, get_data_full, get_all_generations

# Blueprint for the Who's That Pokémon game views and logic
wtp_bp = Blueprint('whos_that_pkmn', __name__, template_folder='../templates')

# Retrieve all available generations from configuration (config.py)
all_generations = get_all_generations()

# Serve the home page for the Who's That Pokémon game, which includes instructions and settings.
# Also, clear any existing game session data to ensure a fresh start for the user.
@wtp_bp.route('/whos_that_pkmn_home', methods=['GET', 'POST'])
def home():
    clean_session('all')
    return render_template('whos_that_pkmn_home.html')

# Route to initiate and handle gameplay interactions for the Who's That Pokémon game.
# It presents the game interface to the user and processes their input during the game.
@wtp_bp.route('/whos_that_pkmn', methods=['GET', 'POST'])
def start_game():
    # Retrieve the full database
    data_full = get_data_full()

    # Retrieve user game settings
    if request.method == 'POST':
        if 'gen' not in session:
            session['gen']  = request.form.getlist('gen[]')
        
        # If the game has ended, redirect to the score page
        result = game_end('wtp')
        if result:
            return result
    
    # Clean the session cache
    clean_session('reset_wtp')

    # Initialize the score count
    session['score'] = 0
    # Retrieve the user's high score, or initialize it as 0 if it's the user's first game
    session['high_score_wtp'] = session.get('high_score_wtp', 0)
    # Retrieve the list of already drawn Pokémon IDs; initialize as an empty list if none
    session['list_id'] = session.get('list_id', [])
    
    # Retrieve the list of generations selected by the user; default to all generations if none are selected
    generation = session.get('gen', all_generations)
    # Filter the database based on the generations selected by the user
    data = data_full.query('generation in @generation')

    # Draw Pokemon
    pkmn = sort_pkmn(data)

    # Retrieve the list of user correct answers; initialize as an empty list if none
    session['pkmn_list'] = session.get('pkmn_list', [])
    # Create a dictionary with the Pokémon's id-name, and the respective generation
    # This dictionary is used to record the user's answer history
    guessed_pkmn = guessed_pkmn = {
        "id_name": pkmn.id_name,
        "generation": data[data['id'] == pkmn.id]['generation_summary'].iloc[0]
    }
    session['pkmn_list'].append(guessed_pkmn)
    generations_dict = data.groupby('generation_summary')['id_name'].apply(list).to_dict()

    return render_template('whos_that_pkmn.html', pkmn=pkmn, generations_dict = generations_dict, high_score_wtp=session.get('high_score_wtp', 0))

@wtp_bp.route('/redraw_pokemons_wtp', methods=['GET', 'POST'])
def redraw_pokemons():
    # Retrieve the full database
    data_full = get_data_full()

    # Increase user score by 1
    session['score'] += 1

    # Variable to flag if the game ended
    game_end = 'False'

    # Retrieve the list of generations selected by the user; default to all generations if none are selected
    generation = session.get('gen', all_generations)
    # Filter the database based on the generations selected by the user
    data = data_full.query('generation in @generation')

    # Check if all Pokémons have been encountered to determine if the game has ended
    if len(session.get('list_id', [])) == len(data):
        game_end = 'True'
        return jsonify({'game_end': game_end})

    # Draw new Pokemon
    new_pokemon = sort_pkmn(data)

    # Record user answer history
    guessed_pkmn = guessed_pkmn = {
        "id_name": new_pokemon.id_name,
        "generation": data[data['id'] == new_pokemon.id]['generation_summary'].iloc[0]
    }
    session['pkmn_list'].append(guessed_pkmn)

    return jsonify({
        'game_end': game_end,
        'id': new_pokemon.id,
        'name': new_pokemon.name,
        'id_name': new_pokemon.id_name,
        'sprite': new_pokemon.sprite,
        'shadow_sprite': new_pokemon.shadow_sprite
    })

app/templates/higher_lower.html
{% extends "template.html" %}
{% block content%}
<header class="header">
    <nav class="header_menu">
        <div class = "nav_menu">
            <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
            <p class="header_menu_link header_menu_link_selected">Higher Lower Game</p>
            <a class="header_menu_link" href="{{ url_for('whos_that_pkmn.home') }}">Who's that Pokémon</a>
        </div>
        <div class = "nav_menu_drop_list">
            <input type="checkbox" id="menu" class="container__button">
            <label for="menu" class="container__label">
                <span class="header_menu_icon container__imagem"></span>
            </label>
            <ul class="lista-menu">
                <li class="lista-menu__item">
                    <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
                </li>
                <li class="lista-menu__item">
                    <a class="header_menu_link" href="{{ url_for('whos_that_pkmn.home') }}">Who's that Pokémon</a>
                </li>
            </ul>
        </div>
        <div class = "toogle_menu">
            <img src="{{ url_for('static', filename='assets/sun.png') }}" alt="Day Mode" class="toggle_icon">
            <label class="toggle-btn">
                <input type="checkbox" id="toggleBackground">
                <span class="slider"></span>
            </label>
            <img src="{{ url_for('static', filename='assets/moon.png') }}" alt="Night Mode" class="toggle_icon">
        </div>
    </nav>
</header>

<main class="main_content">

    <section class="pokemon_battle">
        <div class="pokemon_hl" id="pkmn-1"> 
            <h2 class="main_content_title">{{ pkmn_1.name }}</h2>
            <img src="{{ pkmn_1.sprite }}" alt="Pokemon 1" data-stat="{{ pkmn_1.stat }}">
            <h3 class="main_content_title" id="stat-pkmn-1"></h3>
        </div>
        <div> 
            <h1 class="main_content_title" id="stat">{{ stat }}</h1>
            <div class="score-container">
                <h2 class="main_content_text" id="score">Score: 0</h2>
                <h2 class="main_content_text" id="high_score">High Score: {{high_score_hl}}</h2>
            </div>
        </div>
        <div class="pokemon_hl" id="pkmn-2"> 
            <h2 class="main_content_title">{{ pkmn_2.name }}</h2>
            <img src="{{ pkmn_2.sprite }}" alt="Pokemon 2" data-stat="{{ pkmn_2.stat }}">
            <h3 class="main_content_title" id="stat-pkmn-2"></h3>
        </div>
    </section>
    <div id="confirmModal" class="modal">
        <div class="modal-content">
            <p>Are you sure you want to exit? You'll lose your current progress!</p>
            <button class="confirmation_button" id="confirmYes">Yes</button>
            <button class="confirmation_button" id="confirmNo">No</button>
        </div>
    </div>
</main>

<script src="{{ url_for('static', filename='js/higher_lower_game.js') }}"></script>

{% endblock %}

app/templates/higher_lower_home.html
{% extends "template.html" %}
{% block content%}
    <header class="header">
        <nav class="header_menu">
            <div class = "nav_menu">
                <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
                <p class="header_menu_link header_menu_link_selected">Higher Lower Game</p>
                <a class="header_menu_link" href="{{ url_for('whos_that_pkmn.home') }}">Who's that Pokémon</a>
            </div>
            <div class = "nav_menu_drop_list">
                <input type="checkbox" id="menu" class="container__button">
                <label for="menu" class="container__label">
                    <span class="header_menu_icon container__imagem"></span>
                </label>
                <ul class="lista-menu">
                    <li class="lista-menu__item">
                        <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
                    </li>
                    <li class="lista-menu__item">
                        <a class="header_menu_link" href="{{ url_for('whos_that_pkmn.home') }}">Who's that Pokémon</a>
                    </li>
                </ul>
            </div>
            <div class = "toogle_menu">
                <img src="{{ url_for('static', filename='assets/sun.png') }}" alt="Day Mode" class="toggle_icon">
                <label class="toggle-btn">
                    <input type="checkbox" id="toggleBackground">
                    <span class="slider"></span>
                </label>
                <img src="{{ url_for('static', filename='assets/moon.png') }}" alt="Night Mode" class="toggle_icon">
            </div>
        </nav>
    </header>
    <main class="main_content">
        <h1 class="main_content_title">Higher Lower Game</h1>
        <h2 class="main_content_title">Rules</h2>
        <p class="main_content_text">
            Your task is to determine which Pokémon has the superior attribute. 
            As the game progresses, a new Pokémon will be presented to you — without any repeats. 
            Make your choice based on the displayed attribute, which is randomly chosen from your selected settings. 
            Both the attribute and Pokémon choices are guided by your game settings.  
            Aim to consecutively choose correctly and see how many you get right in a row!
        </p>
        
        <form action="/higher_lower" method="post" class="forms" id = "gameForm">
            <h2 class="main_content_title">Settings</h2>
            <fieldset>
                <legend>Select the Generations</legend>
                <div class="scrollable-list">
                    <div class="item-list">
                        <input type="checkbox" id="select-all-gen" name="select-all-gen" value="select-all-gen">
                        <label for="select-all-gen">All Gen's</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-I" name="gen[]" value="generation-i">
                        <label for="gen-I">Gen I</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-II" name="gen[]" value="generation-ii">
                        <label for="gen-II">Gen II</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-III" name="gen[]" value="generation-iii">
                        <label for="gen-III">Gen III</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-IV" name="gen[]" value="generation-iv">
                        <label for="gen-IV">Gen IV</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-V" name="gen[]" value="generation-v">
                        <label for="gen-V">Gen V</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-VI" name="gen[]" value="generation-vi">
                        <label for="gen-VI">Gen VI</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-VII" name="gen[]" value="generation-vii">
                        <label for="gen-VII">Gen VII</label>
                    </div>
                    <div class="item-list">
                        <input type="checkbox" id="gen-VIII" name="gen[]" value="generation-viii">
                        <label for="gen-VIII">Gen VIII</label>
                    </div>
                </div>
            </fieldset>

        <fieldset>
            <legend>Select the Attributes</legend>
            <div class="scrollable-list">
                <div class="item-list">
                    <input type="checkbox" id="select-all-attributes" name="select-all-attributes" value="select-all-attributes">
                    <label for="select-all-attributes">All Attributes</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-height" name="attributes[]" value="Height (cm)">
                    <label for="attribute-height">Height (cm)</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-weight" name="attributes[]" value="Weight (Kg)">
                    <label for="attribute-weight">Weight (Kg)</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-hp" name="attributes[]" value="HP">
                    <label for="attribute-hp">HP</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-attack" name="attributes[]" value="Attack">
                    <label for="attribute-attack">Attack</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-defense" name="attributes[]" value="Defense">
                    <label for="attribute-defense">Defense</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-special-attack" name="attributes[]" value="Sp. Attack">
                    <label for="attribute-special-attack">Sp. Attack</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-special-defense" name="attributes[]" value="Sp. Defense">
                    <label for="attribute-special-defense">Sp. Defense</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-speed" name="attributes[]" value="Speed">
                    <label for="attribute-speed">Speed</label>
                </div>
                <div class="item-list">
                    <input type="checkbox" id="attribute-total" name="attributes[]" value="Total">
                    <label for="attribute-total">Total</label>
                </div>

            </div>
        </fieldset>
        <input type="submit" value="Play">
        </form>

    </main>

    <script src="{{ url_for('static', filename='js/higher_lower_home.js') }}"></script>
    
{% endblock %}

app/templates/index.html
{% extends "template.html" %}
{% block content%}
    <header class="header">
        <nav class="header_menu">
            <div class = "nav_menu">
            </div>
            <div class = "nav_menu_drop_list">
            </div>
            <div class = "toogle_menu">
                <img src="{{ url_for('static', filename='assets/sun.png') }}" alt="Day Mode" class="toggle_icon">
                <label class="toggle-btn">
                    <input type="checkbox" id="toggleBackground">
                    <span class="slider"></span>
                </label>
                <img src="{{ url_for('static', filename='assets/moon.png') }}" alt="Night Mode" class="toggle_icon">
            </div>
        </nav>
    </header>
    <main class="main_content">
        <h1 class="main_content_title">Poke Games</h1>
        <p class="main_content_text">Come challenge your Pokémon knowledge with games!</p>
        <p class="main_content_text">Let's play!</p>
        <div class="main_content_links">
            <a class="main_content_links_item" href="{{ url_for('higher_lower.home') }}">
                High Lower Game
            </a>
            <a class="main_content_links_item" href="{{ url_for('whos_that_pkmn.home') }}">
                Who's that Pokémon
            </a>
        </div>
    </main>
{% endblock %}

app/templates/whos_that_pkmn.html
{% extends "template.html" %}
{% block content%}
<header class="header">
    <nav class="header_menu">
        <div class = "nav_menu">
            <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
            <a class="header_menu_link" href="{{ url_for('higher_lower.home') }}">Higher Lower Game</a>
            <p class="header_menu_link header_menu_link_selected">Who's that Pokémon</p>
        </div>
        <div class = "nav_menu_drop_list">
            <input type="checkbox" id="menu" class="container__button">
            <label for="menu" class="container__label">
                <span class="header_menu_icon container__imagem"></span>
            </label>
            <ul class="lista-menu">
                <li class="lista-menu__item">
                    <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
                </li>
                <li class="lista-menu__item">
                    <a class="header_menu_link" href="{{ url_for('higher_lower.home') }}">Higher Lower Game</a>
                </li>
            </ul>
        </div>
        <div class = "toogle_menu">
            <img src="{{ url_for('static', filename='assets/sun.png') }}" alt="Day Mode" class="toggle_icon">
            <label class="toggle-btn">
                <input type="checkbox" id="toggleBackground">
                <span class="slider"></span>
            </label>
            <img src="{{ url_for('static', filename='assets/moon.png') }}" alt="Night Mode" class="toggle_icon">
        </div>
    </nav>
</header>

<main class="main_content">
    <section class="pokemon_wtp" id="pkmn">
        <div class = 'guess_pkmn'> 
            <h2 class="main_content_text" id="name_pkmn">?</h2>
            <img src="{{ pkmn.shadow_sprite }}" alt="Pokemon" id_name="{{ pkmn.id_name }}" id="pokemonImage" sprite="{{pkmn.sprite}}">
        </div>

        <form action="/whos_that_pkmn" method="post" id="gameForm" class="forms_guess">
            <div class="score-container">
                <h2 class="main_content_text" id="score">Score: 0</h2>
                <h2 class="main_content_text" id="high_score">High Score: {{high_score_wtp}}</h2>
            </div>
            <select id="generation-filter">
                <option value="All">All Generations</option>
                {% for gen in generations_dict.keys() %}
                <option value="{{ gen }}">{{ gen }}</option>
                {% endfor %}
            </select>
            <input type="text" id="global-filter" placeholder="Filter Pokémon Name">
            <div class="scrollable-list" id="pokemon-list">
                <!-- items will be populated by JavaScript -->
            </div>
            <input type="submit" value="Guess">
        </form>
    </section>
    
    <div id="confirmModal" class="modal">
        <div class="modal-content">
            <p>Are you sure you want to exit? You'll lose your current progress!</p>
            <button class="confirmation_button" id="confirmYes">Yes</button>
            <button class="confirmation_button" id="confirmNo">No</button>
        </div>
    </div>
</main>
<script type="text/javascript">
    let generations_dict = {{ generations_dict | tojson | safe }};
</script>
<script type="text/javascript" src="{{ url_for('static', filename='js/whos_that_pkmn_game.js') }}"></script>
{% endblock %}

app/templates/whos_that_pkmn_home.html
{% extends "template.html" %}
{% block content%}
    <header class="header">
        <nav class="header_menu">
            <div class = "nav_menu">
                <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
                <a class="header_menu_link" href="{{ url_for('higher_lower.home') }}">Higher Lower Game</a>
                <p class="header_menu_link header_menu_link_selected">Who's that Pokémon</p>
            </div>
            <div class = "nav_menu_drop_list">
                <input type="checkbox" id="menu" class="container__button">
                <label for="menu" class="container__label">
                    <span class="header_menu_icon container__imagem"></span>
                </label>
                <ul class="lista-menu">
                    <li class="lista-menu__item">
                        <a class="header_menu_link" href="{{ url_for('home.index') }}">Home</a>
                    </li>
                    <li class="lista-menu__item">
                        <a class="header_menu_link" href="{{ url_for('higher_lower.home') }}">Higher Lower Game</a>
                    </li>
                </ul>
            </div>
            <div class = "toogle_menu">
                <img src="{{ url_for('static', filename='assets/sun.png') }}" alt="Day Mode" class="toggle_icon">
                <label class="toggle-btn">
                    <input type="checkbox" id="toggleBackground">
                    <span class="slider"></span>
                </label>
                <img src="{{ url_for('static', filename='assets/moon.png') }}" alt="Night Mode" class="toggle_icon">
            </div>
        </nav>
    </header>
    <main class="main_content">
        <h1 class="main_content_title">Who's That Pokémon Game</h1>
        <h2 class="main_content_title">Rules</h2>
        <p class="main_content_text">
            Your task is to guess the Pokémon based on its shadow.
            As the game progresses, a new Pokémon will be presented to you — without any repeats.
            Pokémon displayed are guided by your game settings.
            Aim to consecutively choose correctly and see how many you get right in a row!
        </p>
        <form action="/whos_that_pkmn" method="post" class="forms forms_wtp" id = "gameForm">
            <h2 class="main_content_title">Settings</h2>
        
                <fieldset>
                    <legend>Select the Generations</legend>
                    <div class="scrollable-list">
                        <div class="item-list">
                            <input type="checkbox" id="select-all-gen" name="select-all-gen" value="select-all-gen">
                            <label for="select-all-gen">All Gen's</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-I" name="gen[]" value="generation-i">
                            <label for="gen-I">Gen I</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-II" name="gen[]" value="generation-ii">
                            <label for="gen-II">Gen II</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-III" name="gen[]" value="generation-iii">
                            <label for="gen-III">Gen III</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-IV" name="gen[]" value="generation-iv">
                            <label for="gen-IV">Gen IV</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-V" name="gen[]" value="generation-v">
                            <label for="gen-V">Gen V</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-VI" name="gen[]" value="generation-vi">
                            <label for="gen-VI">Gen VI</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-VII" name="gen[]" value="generation-vii">
                            <label for="gen-VII">Gen VII</label>
                        </div>
                        <div class="item-list">
                            <input type="checkbox" id="gen-VIII" name="gen[]" value="generation-viii">
                            <label for="gen-VIII">Gen VIII</label>
                        </div>
                    </div>
                </fieldset>

            <input type="submit" value="Play">
        </form>

    </main>

    <script src="{{ url_for('static', filename='js/whos_that_pkmn_home.js') }}"></script>
    
{% endblock %}